homepage: "https://sqlite.org/"
main_repo: "https://sqlite.org/src/dir"
language: c
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

