homepage: "https://aicyberchallenge.com/"
language: c
main_repo: "https://github.com/aixcc-challenges/integration-test"

fuzzing_engines:
  - libfuzzer

sanitizers:
  - address

architectures:
  - x86_64
