homepage: "https://gitlab.gnome.org/GNOME/libxml2"
language: c
primary_contact: ""
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl
main_repo: 'https://gitlab.gnome.org/GNOME/libxml2.git'
