apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crs-webservice

resources:
  - namespace.yaml
  - deployment.yaml
  - secrets.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: ghcr-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson
